### ISSUE TITLE
Request multiple scopes

### ISSUE THREAD

**Issue by MehediH** [seanfisher/passport-microsoft#6]
Hi, thank you so much for this project, made my life so much easier!

I just tried to use the strategy on the example app, and when I try to request multiple scopes, the authentication throws an error. For example:
```
passport.use(new MicrosoftStrategy({
  clientID: MICROSOFT_GRAPH_CLIENT_ID,
  clientSecret: MICROSOFT_GRAPH_CLIENT_SECRET,
  callbackURL: "http://localhost:3000/auth/microsoft/callback",
  scope: ['user.read', 'profile']
} ...
```

the code above throws the following error on the authentication flow (on the MSFT login site):

`AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope user.read profile is not valid. openid scope is required.`

I have also tried setting the scope to `scope: 'user.read,profile'` but that does not work either.

And just to be clear, the app is authorised to use these API endpoints on the Azure Portal.

![image](https://user-images.githubusercontent.com/10274434/81969784-666ba900-9616-11ea-82b7-358750b20f36.png)

I am probably doing something wrong, and would appreciate any pointers :) 

Thanks again for your work!

**Comment by seanfisher** [comment]
I'm not in a place to be able to dive in and help troubleshoot too deeply right now, but a couple quick thoughts that may help you troubleshoot.

The [permissions reference](https://docs.microsoft.com/en-us/graph/permissions-reference) says the following: 
> Important The Microsoft Authentication Library (MSAL) currently specifies offline_access, openid, profile, and email by default in authorization and token requests. This means that, for the default case, if you specify these permissions explicitly, Azure AD may return an error.

So, maybe you should be able to get `profile` information without including `profile` explicitly? Not sure if that statement applies in this case.

You could also see if using `https://graph.microsoft.com/user.read` instead of `user.read` works...

Also what if you just add `openid` as another scope, so you have `openid`, `profile`, and `user.read`?

Just some thoughts to try.

**Comment by MehediH** [comment]
Yep, you are right! Thank you :)
